### ISSUE TITLE
Troubles in combining TRIGRS V2.1 with Scoops3D 

### ISSUE THREAD

**Issue by Jackie1-y** [usgs/landslides-trigrs#13]
I have been spending a long time combining TRIGRS V2.1 with Scoops3D for the regional assessment of slope stability.However,I met some problems in the combination.There were some wrong data points in the TRIGRS V2.1's new output file,a ijz format file.As is shown in the Figure 1
![Figure 1](https://user-images.githubusercontent.com/63548283/79821815-443d8d00-83c2-11ea-865e-6219e12b4624.png)(In the Figure 1,the first three columns list i-j-z coordinate values;column four lists pressure head;column five,saturated data.),the heights from surface to the ground always remained same,corresponding to Scoops3D's execution error(Figure 2)
![Figure 2](https://user-images.githubusercontent.com/63548283/79821957-a0a0ac80-83c2-11ea-8f15-d5052eba0808.png)that slip surface fell below defined pressure head data in the i=241  j=179
points.
    I have tried some possible solutions that Scoops3D provides,such as increasing depth of pressure head data or decreasing volume of potential failures.Unfortunately,they both had no effect.
    Thank you for taking the time out of your busy schedule to read my letter.Looking forward to your reply.

**Comment by ghost** [comment]
Please provide more background information.  I don't understand the logic behind the arrangement of nodes in your output:  In figure 1 it appears that there are 10 surface or near surface nodes all with the same elevation.  The deep node appears to be 1000 m(?) deeper than the surface nodes.   If possible upload a copy of the tr_in.txt file.

**Comment by Jackie1-y** [comment]
Dear Mr Baum,
    I'm really sorry for replying to your message so late today.In the tr_in.txt file,the nzs is 10 and the depth below ground surface is 1000m.What' more, the tr_in.txt file is attached.
    Looking forward to your reply.
                                                                                                                                        Sincerely yours,
                                                                                                                                        Jackie
[tr_in.txt](https://github.com/usgs/landslides-trigrs/files/4603325/tr_in.txt)

**Comment by ghost** [comment]
Thanks for your reply.  No worries about the delay.   I'm sorry it's taken me several days to reply also.  

Does your zmax.asc file contain grid cells where the value of zmax is zero (no soil)?  If zmax=0. at location  i= 241, j=179, then the z-step would become zero, which seems like the most plausible explanation for the erroneous results you reported in which there were ten identical values of I, j, z, p, and chi, all apparently at the ground surface.  The simple workaround in that case would be to make sure that all values of zmax > 0, so that TRIGRS can compute values at equally spaced intervals between the ground surface and zmax, in addition to the deep value 1000 m below the ground surface.

**Comment by Jackie1-y** [comment]
First thank you for your understanding very much.Next I checked my zmax.asc fie and found there were indeed some grid cells where the values of zmax were zero. But I can't be sure zmax=0 in the i=241,j=179 point and I need time to make the data more clearer.Last thank you for your advice.
